version: "3.8"
services:
  php:
    container_name: felixeve
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8777:80"
    volumes:
      - ./www:/var/www/html
    environment:
      $HOME: "~"
      VIRTUAL_HOST: "felixeve.local.co.uk"
      VIRTUAL_PORT: "80"
      PRIMARY_SITE_DOMAIN: "https://felixeve"
